version: '2'
services:
  web:
    image: rails5-test
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: "bundle exec rails server"
