FROM rails5-test:development
MAINTAINER Dan Itsara <dan@glazziq.com>

RUN gem install bundler

ENV RAILS_ENV=production NODE_ENV=production

ADD . $app
RUN bundle install --deployment --clean --without development test
RUN yarn install --pure-lockfile

RUN bundle exec rails assets:clobber assets:precompile tmp:clear
CMD bundle exec rails server -b 0.0.0.0
